// Real output of each tool on a small failing project, paths shortened. Regenerate rather than edit.

export const CARGO_BUILD_FAILED = "   Compiling demo v0.1.0 (/Users/dev/demo)\nerror[E0308]: mismatched types\n --> src/lib.rs:7:5\n  |\n6 | pub fn label(n: i32) -> String {\n  |                         ------ expected `String` because of return type\n7 |     n\n  |     ^- help: try using a conversion method: `.to_string()`\n  |     |\n  |     expected `String`, found `i32`\n\nwarning: unused variable: `unused`\n --> src/lib.rs:2:9\n  |\n2 |     let unused = 3;\n  |         ^^^^^^ help: if this is intentional, prefix it with an underscore: `_unused`\n  |\n  = note: `#[warn(unused_variables)]` on by default\n\nFor more information about this error, try `rustc --explain E0308`.\nwarning: `demo` (lib) generated 1 warning\nerror: could not compile `demo` (lib) due to 1 previous error; 1 warning emitted\n"

export const CARGO_TEST_FAILED = "   Compiling demo v0.1.0 (/Users/dev/demo)\nwarning: unused variable: `unused`\n --> src/lib.rs:2:9\n  |\n2 |     let unused = 3;\n  |         ^^^^^^ help: if this is intentional, prefix it with an underscore: `_unused`\n  |\n  = note: `#[warn(unused_variables)]` on by default\n\nwarning: `demo` (lib) generated 1 warning\nwarning: `demo` (lib test) generated 1 warning (1 duplicate)\n    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.92s\n     Running unittests src/lib.rs (target/debug/deps/demo-5e42db9d41d29817)\n\nrunning 2 tests\ntest tests::adds ... ok\ntest tests::adds_wrong ... FAILED\n\nfailures:\n\n---- tests::adds_wrong stdout ----\n\nthread 'tests::adds_wrong' panicked at src/lib.rs:17:9:\nassertion `left == right` failed: sums should match\n  left: 4\n right: 5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n\n\nfailures:\n    tests::adds_wrong\n\ntest result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s\n\nerror: test failed, to rerun pass `--lib`\n"

export const TSC_FAILED = "src/greet.ts(3,58): error TS2552: Cannot find name 'nam'. Did you mean 'name'?\nsrc/greet.ts(3,71): error TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.\nsrc/maths.ts(5,3): error TS2322: Type 'number' is not assignable to type 'string'.\n"

export const TSC_PRETTY_FAILED = "\u001b[96msrc/greet.ts\u001b[0m:\u001b[93m3\u001b[0m:\u001b[93m58\u001b[0m - \u001b[91merror\u001b[0m\u001b[90m TS2552: \u001b[0mCannot find name 'nam'. Did you mean 'name'?\n\n\u001b[7m3\u001b[0m export const greet = (name: string): string => `Hello, ${nam}!` + add('1', 2)\n\u001b[7m \u001b[0m \u001b[91m                                                         ~~~\u001b[0m\n\n  \u001b[96msrc/greet.ts\u001b[0m:\u001b[93m3\u001b[0m:\u001b[93m23\u001b[0m\n    \u001b[7m3\u001b[0m export const greet = (name: string): string => `Hello, ${nam}!` + add('1', 2)\n    \u001b[7m \u001b[0m \u001b[96m                      ~~~~~~~~~~~~\u001b[0m\n    'name' is declared here.\n\n\u001b[96msrc/greet.ts\u001b[0m:\u001b[93m3\u001b[0m:\u001b[93m71\u001b[0m - \u001b[91merror\u001b[0m\u001b[90m TS2345: \u001b[0mArgument of type 'string' is not assignable to parameter of type 'number'.\n\n\u001b[7m3\u001b[0m export const greet = (name: string): string => `Hello, ${nam}!` + add('1', 2)\n\u001b[7m \u001b[0m \u001b[91m                                                                      ~~~\u001b[0m\n\n\u001b[96msrc/maths.ts\u001b[0m:\u001b[93m5\u001b[0m:\u001b[93m3\u001b[0m - \u001b[91merror\u001b[0m\u001b[90m TS2322: \u001b[0mType 'number' is not assignable to type 'string'.\n\n\u001b[7m5\u001b[0m   return n\n\u001b[7m \u001b[0m \u001b[91m  ~~~~~~\u001b[0m\n\n\nFound 3 errors in 2 files.\n\nErrors  Files\n     2  src/greet.ts\u001b[90m:3\u001b[0m\n     1  src/maths.ts\u001b[90m:5\u001b[0m\n"

export const ESLINT_FAILED = "\n/Users/dev/demo/src/lint.js\n  1:1   warning  Unexpected var, use let or const instead     no-var\n  1:5   error    'unused' is assigned a value but never used  no-unused-vars\n  2:33  error    'missing' is not defined                     no-undef\n\n✖ 3 problems (2 errors, 1 warning)\n  0 errors and 1 warning potentially fixable with the `--fix` option.\n\n"

export const VITEST_FAILED = "\n RUN  v5.0.3 /Users/dev/demo\n\n ❯ src/maths.test.js (2 tests | 1 failed) 3ms\n   ❯ maths (2)\n     × adds wrong 2ms\n\n⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯\n\n FAIL  src/maths.test.js > maths > adds wrong\nAssertionError: expected 4 to be 5 // Object.is equality\n\n- Expected\n+ Received\n\n- 5\n+ 4\n\n ❯ src/maths.test.js:5:48\n      3| describe('maths', () => {\n      4|   test('adds', () => { expect(add(2, 2)).toBe(4) })\n      5|   test('adds wrong', () => { expect(add(2, 2)).toBe(5) })\n       |                                                ^\n      6| })\n      7|\n\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯\n\n\n Test Files  1 failed (1)\n      Tests  1 failed | 1 passed (2)\n   Start at  08:47:21\n   Duration  73ms (transform 50%, import 23%, tests 19%, worker 8%)\n\n"

export const JEST_FAILED = "FAIL jt/maths.test.cjs\n  ● maths › adds wrong\n\n    expect(received).toBe(expected) // Object.is equality\n\n    Expected: 5\n    Received: 4\n\n      2 | describe('maths', () => {\n      3 |   test('adds', () => { expect(add(2, 2)).toBe(4) })\n    > 4 |   test('adds wrong', () => { expect(add(2, 2)).toBe(5) })\n        |                                                ^\n      5 | })\n      6 |\n\n      at Object.<anonymous> (maths.test.cjs:4:48)\n\nTest Suites: 1 failed, 1 total\nTests:       1 failed, 1 passed, 2 total\nSnapshots:   0 total\nTime:        0.078 s\nRan all test suites.\n"

// Written by hand in each tool's documented output format: the tool is not installed where these were made.

export const PYTEST_FAILED = "============================= test session starts ==============================\nplatform darwin -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0\nrootdir: /Users/dev/demo\ncollected 3 items\n\ntests/test_maths.py .F.                                                  [100%]\n\n=================================== FAILURES ===================================\n________________________________ test_adds_wrong _______________________________\n\n    def test_adds_wrong():\n>       assert add(2, 2) == 5\nE       assert 4 == 5\nE        +  where 4 = add(2, 2)\n\ntests/test_maths.py:9: AssertionError\n=========================== short test summary info ============================\nFAILED tests/test_maths.py::test_adds_wrong - assert 4 == 5\n========================= 1 failed, 2 passed in 0.03s ==========================\n"

export const PYTEST_PASSED = "============================= test session starts ==============================\nplatform darwin -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0\nrootdir: /Users/dev/demo\ncollected 240 items\n\ntests/test_mod_1.py ........................                            [ 10%]\ntests/test_mod_2.py ........................                            [ 20%]\ntests/test_mod_3.py ........................                            [ 30%]\ntests/test_mod_4.py ........................                            [ 40%]\ntests/test_mod_5.py ........................                            [ 50%]\ntests/test_mod_6.py ........................                            [ 60%]\ntests/test_mod_7.py ........................                            [ 70%]\ntests/test_mod_8.py ........................                            [ 80%]\ntests/test_mod_9.py ........................                            [ 90%]\ntests/test_mod_10.py ........................                            [100%]\n\n============================= 240 passed in 4.12s ==============================\n"

export const GO_TEST_FAILED = "=== RUN   TestAdd\n--- PASS: TestAdd (0.00s)\n=== RUN   TestAddWrong\n    maths_test.go:14: add(2, 2) = 4, want 5\n--- FAIL: TestAddWrong (0.00s)\nFAIL\nFAIL\tdemo/maths\t0.214s\nok  \tdemo/greet\t0.105s\nFAIL\n"

export const GO_BUILD_FAILED = "# demo/maths\n./maths.go:7:9: cannot use n (variable of type int) as string value in return statement\n./maths.go:11:2: declared and not used: unused\n"

export const GRADLE_FAILED = "> Task :app:compileKotlin FAILED\ne: file:///Users/dev/demo/app/src/main/kotlin/Maths.kt:7:12 Type mismatch: inferred type is Int but String was expected\nw: file:///Users/dev/demo/app/src/main/kotlin/Maths.kt:3:9 Variable 'unused' is never used\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nExecution failed for task ':app:compileKotlin'.\n> Compilation error. See log for more details\n\nBUILD FAILED in 2s\n3 actionable tasks: 2 executed, 1 up-to-date\n"

export const MYPY_FAILED = "src/maths.py:7: error: Incompatible return value type (got \"int\", expected \"str\")  [return-value]\nsrc/greet.py:3:12: error: Name \"nam\" is not defined  [name-defined]\nFound 2 errors in 2 files (checked 4 source files)\n"

export const RUFF_FAILED = "src/maths.py:1:8: F401 [*] `os` imported but unused\nsrc/maths.py:4:89: E501 Line too long (104 > 88)\nFound 2 errors.\n[*] 1 fixable with the `--fix` option.\n"

export const UNREADABLE_FAILED = "Traceback (most recent call last):\n  File \"build.py\", line 3, in <module>\n    main()\nRuntimeError: the bundler crashed\n"
